### PR TITLE
Directly return stream from CreateReadStream

### LINKED ISSUE #18: Out of memory exception when downloading large files from Blob
Hi

Based on application insights logs, the following method throws ```System.OutOfMemoryException``` exception when downloading files larger than 350Mb on an Azure web app running on 3.5Gb (S2 service plan)

[Edit: it's not that crazy... it's 350Mb :)]

```Strathweb.AspNetCore.AzureBlobFileProvider.AzureBlobFileInfo.CreateReadStream```

I'll attach the full stack trace in a separate file:
[fullstacktrace.txt](https://github.com/filipw/Strathweb.AspNetCore.AzureBlobFileProvider/files/3416531/fullstacktrace.txt)

I'm not sure if this is intended to be used for large files, but it sure would be a **great** and **powerful** feature if it could be used like that!

### PR DESCRIPTION
**Pull request by kdubau**
Fixes #18 ?

### CODE REVIEW

**Comment by kdubau** [comment]
@johnayling thoughts?

**Comment by johnayling** [comment]
I've used this way to download very large files from Azure without doubling up with a memory stream.

public async Task<FileStreamResult> CreateReadStream() 
{
     var stream = await _blockBlob.OpenReadAsync();
     return new FileStreamResult(stream, "application/octet-stream");
}

**Comment by ibruynin** [comment]
Curious if there is a way to test this pull request.
There are no unofficial prerelease nugets available right?

**Comment by ibruynin** [comment]
@filipw - Quick note. I forked this change and it behaves well in production now.
also fixes #18 - so it seems

**Comment by kdubau** [comment]
I'm closing this since the author never accepted it.

**Pull request closed without merging**
